# Generated by Django 5.2 on 2025-04-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objects',
            new_name='Offers',
        ),
    ]
